MyGroups/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from django.views.i18n import JavaScriptCatalog




urlpatterns = [
    path('admin/', admin.site.urls),
    path('grupos/', include('main.urls')),
    path('', RedirectView.as_view(url='/grupos/', permanent=True)),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^grupos/', include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url("listagrupos", views.GrupoListView.as_view(), name='listagrupos'),
    url("listasolicitudes", views.SolicitudListView.as_view(), name='listasolicitudes'),
    #url("detallegrupo(?P<pk>\d+)$", views.InfoGrupoView.as_view(), name='detallegrupo'),
    #url("detallegrupo(?P<pk>\d+)$/actualizado", views.InfoGrupoView.as_view(), name='detallegrupo'),
    #url("calendario", views.calendarpage, name='calendarpage'),

    path("calendario2?gruposHCR=gruposHCR", views.calendarpage, name='calendarpage2'),
    path("calendario2", views.calendarpage, name='calendarpage'),
    url("nuevogrupo", views.nuevogrupo, name='nuevogrupo'),
    path("detallegrupo<pk>", views.infogrupo, name='detallegrupo'),
    url("solicitudgrupo(?P<pk>\d+)$", views.solicitudgrupo, name='solicitudgrupo'), #crea solicitud
    url("detallesolicitud(?P<pk>\d+)$", views.cotizacion, name='detallesolicitud'), #cotización para solicitud
    path("reservacotizacion<pk>", views.reservacotizacion, name='reservacotizacion'),    #confirma reserva solicitud
    url("warnings", views.warnings, name='warnings'),
    url("actualizado", views.actualizar, name='actualizar'),
    path("sindisponibilidad<pk>", views.sindisponibilidad, name='sindisponibilidad'),
    path("cotizacion<pk>", views.modificarcotizacion, name='cotizacion'),
    path("modificargrupo<pk>", views.modificargrupo, name='modificargrupo'),
    url("nuevaagencia", views.nuevaagencia, name = "nuevaagencia"),

]

main/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Requerida para las instancias de libros únicos
import datetime
import numpy as np

from django.utils import timezone

hoteles=['HCR', 'HCL', 'HM', 'NE']

class Solicitud(models.Model):

    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para esta solicitud")
    title = models.CharField(blank=True, max_length=100)
    grupo = models.ForeignKey('Grupo', on_delete=models.SET_NULL, null=True)
    agencia = models.ForeignKey('Agencia', on_delete=models.SET_NULL, null=True)
    calendario      = models.ForeignKey('Calendar', on_delete=models.SET_NULL, null=True, blank=True)
    comentarios     = models.TextField(blank=True)
    recibida = models.DateField()
    registrada = models.DateField()
    asuntocorreo=models.CharField(blank=True, max_length=100)
    correo=models.TextField(blank=True)

    LOAN_STATUS = (
        ('d', 'Cotizada pero no va a reservar'),
        ('n', 'Sin disponibilidad'),
        ('p', 'Pendiente'),
        ('r', 'Cotizada, podría reservar'),
        ('R', 'Reservada (borrar)'),
        ('A', 'Reservada y anulada')
    )

    solicitudHCR=models.BooleanField(default=False)
    solicitudHCL=models.BooleanField(default=False)
    solicitudHM=models.BooleanField(default=False)



    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='p', help_text='Estado de la solicitud')




    class Meta:
        ordering = ["registrada"]

    def avgprice(self):
        entrada=self.grupo.entrada
        salida=self.grupo.salida
        calendario = self.calendario

        last_update = Calendar.objects.order_by('-updated')[0]
        prueba=last_update.updated-datetime.timedelta(seconds=1)
        last_calendar = Calendar.objects.filter(updated__gt=prueba)
        # it might be a good idea to inspect the result at this point
        # to ensure you are deleting the right stuff



        dias=last_calendar.filter(day__range=[entrada, salida])
        HCLprices=[]
        HMprices=[]
        HCRprices=[]
        for dia in dias:
            HCLprices.append(dia.HCLprice)
            HMprices.append(dia.HMprice)
            HCRprices.append(dia.HCRprice)

        avgHCLprice=np.mean(HCLprices)
        avgHMprice =np.mean(HMprices)
        avgHCRprice=np.mean(HCRprices)

        context={'avgHCLprice': avgHCLprice, 'avgHMprice': avgHMprice, 'avgHCRprice': avgHCRprice}

        avgprices=[x for x in context.values()]

        return avgprices



    def __str__(self):
        """
        String para representar el Objeto del Modelo
        """
        return '%s (%s)' % (self.id,self.title)

    """
    def get_absolute_url(self):

        return reverse('solicitud', args=[str(self.id)])
    """

    def save(self, *args, **kwargs):

        #self.avgprice = self.avgprice(self)
        return super(Solicitud, self).save(*args, **kwargs)

    def get_absolute_url(self):

        return reverse('detallesolicitud', kwargs={ 'pk': str(self.id)})

    def reserva_url(self):

        return reverse('reservasolicitud', kwargs={ 'pk': str(self.id)})

    def contar(self):
        num_cotizaciones = Cotizacion.objects.filter(solicitud=self).count()
        return num_cotizaciones


class Cotizacion(models.Model):
    solicitud=models.ForeignKey('Solicitud', on_delete=models.SET_NULL, null=True)

    cotizacionSA    = models.FloatField(default= 0, blank=True)
    cotizacionHAB   = models.FloatField(default= 0, blank=True)
    cotizacionAD    = models.FloatField(default= 0, blank=True)
    cotizacionMP    = models.FloatField(default= 0, blank=True)
    cotizacionPC    = models.FloatField(default= 0, blank=True)

    num_reserva = models.CharField(default= '', blank=True, max_length=20)

    HOTELES = (
        ('HCR', 'Hotel Carlton Rioja'),
        ('HCL', 'Hotel Ciudad de Logroño'),
        ('HM', 'Hotel Murrieta'),
        )

    hotel = models.CharField(max_length=3, choices=HOTELES, default='HM', help_text='Hotel que envía la solicitud',blank=True)

    disponibilidad =models.BooleanField(default=True)


    enviada=models.DateTimeField(blank=True, null=True)
    reservada=models.BooleanField(default=False)





class Grupo(models.Model):


    title = models.CharField(max_length=400, blank=True)

    #author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.
    entrada=models.DateField()
    salida =models.DateField()
    pax    =models.IntegerField(default=0, blank=True)
    dobles =models.IntegerField(default=0, blank=True)
    triples=models.IntegerField(default=0, blank=True)
    DUIs   =models.IntegerField(default=0, blank=True)
    singles=models.IntegerField(default=0, blank=True)
    comentarios = models.TextField(default="",max_length=1000, blank=True,help_text="Comentarios adicionales")

    NE=models.BooleanField()
    SA=models.BooleanField()
    AD=models.BooleanField()
    MP=models.BooleanField()
    PC=models.BooleanField()

    registrado=models.DateField(default=datetime.date.today)


    BOOKING_STATUS = (
        ('HCR', 'Reservado en HCR'),
        ('HCL', 'Reservado en HCL'),
        ('HM', 'Reservado en HM'),
        ('CER', 'Cotizado, esperando respuesta'),
        ('CNR', 'Cotizado, no reserva'),
        ('SD', 'Sin disponibilidad'),
        ('NA', 'No atendido')
    )

    reservado = models.CharField(max_length=3, choices=BOOKING_STATUS, blank=True, default='NA', help_text='Estado del grupo')


    def __str__(self):
        """
        String que representa al objeto Book
        """
        return '%s (%s,%s,%s)' % (self.id,self.entrada,self.salida, self.title)

    def formatentrada(self):
        year=str(self.entrada.year)
        month='0'+str(self.entrada.month) if self.entrada.month<10 else str(self.entrada.month)
        day='0'+str(self.entrada.day) if self.entrada.day<10 else str(self.entrada.day)
        date=year+'-'+month+'-'+day
        return date

    def formatsalida(self):
        year=str(self.salida.year)
        month='0'+str(self.salida.month) if self.salida.month<10 else str(self.salida.month)
        day='0'+str(self.salida.day) if self.salida.day<10 else str(self.salida.day)
        date=year+'-'+month+'-'+day
        return date

    def contarsolicitudes(self):
        num_solicitudes = Solicitud.objects.filter(grupo=self).count()
        return num_solicitudes

    def get_absolute_url(self):

        return reverse('detallegrupo', kwargs={ 'pk': str(self.id)})


    def save(self, *args, **kwargs):


        super(Grupo, self).save(*args, **kwargs)
        #return '%s' % (self.noche)



class Agencia(models.Model):
    """
    Modelo que representa una agencia
    """

    nombre = models.CharField(max_length=200, unique=True)

    def __str__(self):

        return self.nombre


    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book
        """
        return reverse('agency-detail', args=[str(self.id)])



class Calendar(models.Model):
    day = models.DateField()

    HCLprice = models.FloatField(default=0,blank=True)
    HCRprice = models.FloatField(default=0,blank=True)
    HMprice = models.FloatField(default=0,blank=True)
    FyGprice = models.FloatField(default=0, blank=True)
    NHprice = models.FloatField(default=0, blank=True)

    HCLrooms = models.IntegerField(default=0,blank=True)
    HCRrooms = models.IntegerField(default=0,blank=True)
    HMrooms = models.IntegerField(default=0,blank=True)

    HCLrooms_lastupdate=models.IntegerField(default=0,blank=True)
    HCLrooms_lastweek=models.IntegerField(default=0,blank=True)
    HCLrooms_lastmonth=models.IntegerField(default=0,blank=True)

    HCRrooms_lastupdate=models.IntegerField(default=0,blank=True)
    HCRrooms_lastweek=models.IntegerField(default=0,blank=True)
    HCRrooms_lastmonth=models.IntegerField(default=0,blank=True)

    HMrooms_lastupdate=models.IntegerField(default=0,blank=True)
    HMrooms_lastweek=models.IntegerField(default=0,blank=True)
    HMrooms_lastmonth=models.IntegerField(default=0,blank=True)

    HCLprice_lastupdate=models.IntegerField(default=0,blank=True)
    HCLprice_lastweek=models.IntegerField(default=0,blank=True)
    HCLprice_lastmonth=models.IntegerField(default=0,blank=True)

    HCRprice_lastupdate=models.IntegerField(default=0,blank=True)
    HCRprice_lastweek=models.IntegerField(default=0,blank=True)
    HCRprice_lastmonth=models.IntegerField(default=0,blank=True)

    HMprice_lastupdate=models.IntegerField(default=0,blank=True)
    HMprice_lastweek=models.IntegerField(default=0,blank=True)
    HMprice_lastmonth=models.IntegerField(default=0,blank=True)

    FyGprice_lastupdate=models.IntegerField(default=0,blank=True)
    FyGprice_lastweek=models.IntegerField(default=0,blank=True)
    FyGprice_lastmonth=models.IntegerField(default=0,blank=True)

    NHprice_lastupdate=models.IntegerField(default=0,blank=True)
    NHprice_lastweek=models.IntegerField(default=0,blank=True)
    NHprice_lastmonth=models.IntegerField(default=0,blank=True)

    diasem=models.CharField(default='', max_length=30, blank=True)

    updated=models.DateTimeField(blank=True,null=True)
    precio3stars=models.FloatField(blank=True)
    #precio4stars=models.FloatField(blank=True)


    def formatday(self):
        year    =   str(self.day.year)
        month   ='0'+str(self.day.month) if self.day.month<10 else str(self.day.month)
        day     ='0'+str(self.day.day)   if self.day.day<10 else str(self.day.day)
        date    = year+'-'+month+'-'+day
        return date

    def HCLdayprice(self):


        HCLprice=str(int(self.HCLprice))

        HCLrooms=str(self.HCLrooms)

        HCLdayprice = HCLrooms+' '+HCLprice+'€'

main/forms.py
from django.forms import ModelForm, TextInput
from .models import Grupo, Solicitud, Cotizacion, Agencia
from django.contrib.admin.widgets import AdminDateWidget
from django.core.exceptions import ValidationError
import datetime



class GrupoForm(ModelForm):

    class Meta:
        model = Grupo
        fields = [ 'title','entrada', 'salida', 'pax', 'triples', 'DUIs', 'singles', 'comentarios', 'NE','SA','AD','MP','PC']
        widgets = {
            'entrada': AdminDateWidget(),
            'salida': AdminDateWidget(),
            'title': TextInput(attrs={
                    'placeholder': 'Nombre (opcional)'
                    })
            }
    def clean(self):
        cleaned_data = super().clean()
        entrada = cleaned_data.get("entrada")
        salida = cleaned_data.get("salida")

        if salida <= entrada:
            raise ValidationError(
                "¡Error! La fecha de salida no puede ser igual o anterior a la fecha de entrada."
            )

        elif salida - entrada > datetime.timedelta(weeks=2):
            raise ValidationError(
                "¡Error! No se admiten grupos de más de dos semanas."
            )



class SolicitudForm(ModelForm):
    class Meta:
        model = Solicitud
        fields = ['title','agencia', 'recibida', 'registrada', 'solicitudHM','solicitudHCL','solicitudHCR', 'comentarios', 'correo', 'asuntocorreo']
        widgets = {
            'recibida': AdminDateWidget(),
            'registrada': AdminDateWidget(),
            'correo': TextInput(attrs={
                    'style': 'width: 600px; height: 400px;',
                    'placeholder': 'Cuerpo'
                    }),
            'asuntocorreo': TextInput(attrs={
                    'style': 'width: 550px',
                    'placeholder': 'Asunto'
                    }),
            }

        """'name': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Name'
                }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
                })
        }"""




class CotizacionForm(ModelForm):
    class Meta:
      model = Cotizacion
      fields = ['disponibilidad','cotizacionSA', 'cotizacionAD', 'cotizacionMP', 'cotizacionPC', 'cotizacionHAB','hotel']


class AgenciaForm(ModelForm):
    class Meta:
      model = Agencia
      fields = ['nombre']



class SinDisponibilidadForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['disponibilidad']


class ReservaForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields= ['num_reserva']

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script type="text/javascript" src="/jsi18n/"></script>
  <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
  <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

  <!--<link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">-->

  <link href="{% static 'fullcalendar/packages/core/main.css'%}" rel='stylesheet' />
  <link href="{% static 'fullcalendar/packages/daygrid/main.css'%}" rel='stylesheet' />


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'calendarcss/bootstrap.min.css' %}">

  <!-- Style -->
  <link rel="stylesheet" href="{% static 'calendarcss/style.css' %}">

  <!-- Add additional CSS in static file -->

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'listagrupos' %}">Grupos</a></li>
          <li><a href="{% url 'listasolicitudes' %}">Solicitudes</a></li>
          <li><a href="">Agencias</a></li>
          <li><a href="{% url 'calendarpage2' %}">Calendario</a></li>
          <li> <a href="{% url 'nuevogrupo' %}" ><span class="glyphicon glyphicon-plus"></span> Nuevo grupo</a></li>
          <li> <a href="{% url 'warnings' %}" >Revenue</a></li>
          <li> <a href="{% url 'actualizar' %}" >Actualizar</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

main/templates/cotizacion.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <h1>Grupo: {{ grupo.title }}</h1>
  <h1>Solicitud: {{ solicitud.title }}</h1>

  {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="{{bottontext}}">
  </form>
{% endblock %}

main/templates/listagrupos.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista grupos</h1>

    {% if grupo_list %}

    <table>

    <tr>
      <th>Recibido</th>
      <th>Grupo</th>
      <th>ID</th>
      <th>Agencia</th>
      <th>Entrada</th>
      <th>Salida</th>
      <th>PAX</th>
      <th>Regimen</th>
      <th>Festivo</th>
      <th>Estado</th>
    </tr>

    {% for grupo in grupo_list %}


    <tr>
      <td>{{grupo.registrado}}</td>
      <td>{{grupo.title}}</td>
      <td>{{grupo.pk}}</td>
      <td>{{grupo.agencia}}</td>
      <td>{{grupo.entrada}}</td>
      <td>{{grupo.salida}}</td>
      <td>{{grupo.pax}}</td>
      <td>{{grupo.regimen}}</td>
      <td>{{grupo.festivo}}</td>
      <td>{{grupo.get_reservado_display}}</td>
      <td><a href="{{ grupo.get_absolute_url }}">Ver grupo</a></td>
    </tr>
    {% endfor %}


  </table>

    {% else %}
      <p>No hay grupos registrados.</p>
    {% endif %}

{% endblock %}

main/templates/listasolicitudes.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista solicitudes</h1>

    {% if solicitud_list %}
    <ul>

      {% for solicitud in solicitud_list %}
      <li>
        <a>{{ solicitud.id }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

main/templates/solicitudgrupo.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1>Title: {{ grupo.title }}</h1>

  <!-- <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Entrada:</strong> {{ grupo.entrada }}</p>
  <p><strong>Salida:</strong> {{ grupo.salida }}</p>
  <p><strong>Salida:</strong> {{ grupo.pax}}</p>


  <!--
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>-->

  <form method="post">
      {% csrf_token %}

  <div class="row" style="display:flex; margin-right:20px">
    <div class="column" style="flex: 40%; margin-right:10px">
      <div class="form-group">
      {{ form.agencia }}
      </div>
      <div class="form-group">
      {{ form.recibida }}
      </div>
      <div class="form-group">
      {{ form.registrada }}
      </div>
      <div class="form-group">
      {{ form.solicitudHM }}
      {{ form.solicitudHCL }}
      {{ form.solicitudHCR }}
      </div>
      <div class="form-group">
      {{ form.comentarios }}
      </div>
      <input class="btn btn-primary" type="submit" value="Submit">
    </div> <!--termina primera columna-->

    <div class="column" style="flex: 59%;">
      <div class="form-group">
      {{ form.correo }}
      </div>
    </div><!--termina segunda columna-->

  </div><!--termina fila-->
  </form><!--termina form-->

  <div style="margin-left:20px;margin-top:20px">



    <div class="container">
    <h1>Form</h1>
    <form method="post">
        {% csrf_token %}
    <div class="form-group">
        {{ form.correo }}
    </div>

    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Submit">
    </div>
    </form>
</div>


    <h4>Nueva solicitud</h4>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Registrar">
    </form>



    <h4>Solicitudes</h4>

    {% for solicitud in solicitudes %}
    <hr>
    <p class="{% if solicitud.status == 'p' %}text-danger{% elif solicitud.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ solicitud.get_status_display }}</p>
    {% if solicitud.status != 'p' %}<p><strong>Due to be returned:</strong> {{solicitud.due_back}}</p>{% endif %}
    <p><strong>Agencia:</strong> {{solicitud.agencia}}</p>
    <p><strong>Recibida:</strong> {{solicitud.recibida}}</p>
    <p class="text-muted"><strong>Id:</strong> {{solicitud.id}}</p>
    {{solicitud.avgprice}}
    <a href="{{ solicitud.get_absolute_url }}">Cotizar</a>

    {% for cotizacion in cotizaciones %}

    {{cotizacion}}
    {% endfor %}
    {% endfor %}
  </div>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Precios</h4>

    {% for calendario in calendarios%}


    {% if calendario.day >= grupo.entrada and calendario.day < grupo.salida %}
    <p><strong>Día:</strong> {{calendario.day}}</p>
    <p><strong>Habitaciones:</strong> {{calendario.rooms}}</p>
    <p><strong>Precio:</strong> {{calendario.price}}</p>
    <hr>
    {% endif %}
    {% endfor %}
  </div>

  <div class="container">
    Vamoh a veh

  </div>

  <div id='calendar-container'>
    <div id='calendar'></div>
  </div>



    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'fullcalendar/packages/core/main.js' %}"></script>
    <script src="{% static 'fullcalendar/packages/interaction/main.js' %}"></script>
    <script src="{% static 'fullcalendar/packages/daygrid/main.js' %}"></script>
    <script src="{% static 'fullcalendar/packages/timegrid/main.js' %}"></script>
    <script src="{% static 'fullcalendar/packages/list/main.js' %}"></script>








    <script>
      document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
      height: 'parent',
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      defaultView: 'dayGridMonth',
      defaultDate: '{{ grupo.formatentrada }}',
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: false, // allow "more" link when too many events



      events: [
        {% for calendar in calendarios %}

          {
            title: '{{calendar.dayprice}}',
            start: '{{calendar.formatday}}',
            end: '{{calendar.formatday}}',
            color: 'gray',
            textColor: 'green',
            sort:"0",
          },

        {% endfor %}


        {
          title: 'Long Event',
          start: '2021-08-07',
          end: '2021-08-31',
          sort:'3'
        },
        {% for otrogrupo in grupos %}

            {%if grupo.title == otrogrupo.title %}
              {
                title: '{{grupo.title}}',
                start: '{{grupo.formatentrada}}',
                end: '{{grupo.formatsalida}}',
                url: "detallegrupo{{grupo.id}}",
                color: 'black',
                sort:'1'
              },
            {%else %}
              {
                title: '{{otrogrupo.title}}',
                start: '{{otrogrupo.formatentrada}}',
                end: '{{otrogrupo.formatsalida}}',
                url: "detallegrupo{{otrogrupo.id}}",
                color: 'blue',
                sort:'2'
              },
            {% endif %}
        {% endfor %}

    ],




    });

    calendar.render();
  });

    </script>

    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.min.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

{% endblock %}